global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'wal-primary'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wal-primary:8080']
        labels:
          role: 'primary'

  - job_name: 'wal-replica'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wal-replica:8080']
        labels:
          role: 'replica'
